import asyncio
import os
import sys
from datetime import datetime
from mcp_agent.app import MCPApp
from mcp_agent.agents.agent import Agent
from mcp_agent.workflows.llm.augmented_llm_google import GoogleAugmentedLLM

# Configuration values
OUTPUT_DIR = "analysis_reports"
# Files in the same folder as this script
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PNG_FILE_PATH = "..\Parents-in-the-Loop\sample_data\poppy_the_gamer.png"
JSON_FILE_PATH = "..\Parents-in-the-Loop\sample_data\poppy_the_gamer.json"

# Initialize app
app = MCPApp(name="Multi-Modal-Analyzer-Agent")

async def main():
    # Create output directory and set up file paths
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    output_file = f"multimodal_analysis_report_{timestamp}.md"
    output_path = os.path.join(OUTPUT_DIR, output_file)

    async with app.run() as analyzer_app:
        context = analyzer_app.context
        logger = analyzer_app.logger

        # Configure filesystem server to use current directory
        if "filesystem" in context.config.mcp.servers:
            context.config.mcp.servers["filesystem"].args.extend([os.getcwd()])
            logger.info("Filesystem server configured")
        else:
            logger.warning("Filesystem server not configured - report saving may fail")

        # --- CREATE AGENT ---
        multimodal_analyzer_agent = Agent(
            name="multimodal_analyzer",
            instruction=f"""You are an expert analyst specializing in multi-modal data analysis (images + structured data).

            Your task:
            1. Analyze the PNG image: {PNG_FILE_PATH}
            2. Read and analyze the JSON file: {JSON_FILE_PATH}  
            3. Understand how the image and data relate to each other
            4. Extract key insights from both sources
            5. Write a comprehensive summary in bullet-point format

            Analysis requirements:
            - Describe what you see in the PNG image (charts, diagrams, text, etc.)
            - Identify the main data categories and structure in the JSON
            - Find connections between the visual content and the data
            - Highlight key metrics, trends, or important findings from both sources
            - Note any discrepancies or confirmations between image and data

            Output format:
            Create a bullet-point summary with:
            4-6 bullet points for the image analysis and the data analysis.


            Be concise, factual, and focus on the most valuable insights from both the visual and structured data.""",
            server_names=["filesystem"]
        )

        # --- EXECUTE ANALYSIS ---
        logger.info(f"Starting multi-modal analysis of PNG: {PNG_FILE_PATH} and JSON: {JSON_FILE_PATH}")
        
        try:
            async with multimodal_analyzer_agent:
                logger.info("Agent connected, listing available tools...")
                tools = await multimodal_analyzer_agent.list_tools()
                logger.info("Tools available:", data=tools.model_dump())

                # Attach Google LLM to the agent
                llm = await multimodal_analyzer_agent.attach_llm(GoogleAugmentedLLM)
                
                # Run the analysis
                result = await llm.generate_str(
                    message=f"Please analyze both the PNG image '{PNG_FILE_PATH}' and the JSON file '{JSON_FILE_PATH}'. Provide a comprehensive bullet-point summary that covers insights from both sources and how they relate to each other."
                )
                
                # Save the report
                report_content = f"""Multi-Modal Analysis Report
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Source Files: 
- Image: {PNG_FILE_PATH}
- Data: {JSON_FILE_PATH}

Analysis Results

{result}

Report generated by Multi-Modal Analyzer Agent
"""
                
                with open(output_path, 'w', encoding='utf-8') as f:
                    f.write(report_content)
                
                logger.info(f"Analysis complete. Report saved to: {output_path}")
                
        except Exception as e:
            logger.error(f"Analysis failed: {str(e)}")

if __name__ == "__main__":
    # Check if both files exist before running
    missing_files = []
    if not os.path.exists(PNG_FILE_PATH):
        missing_files.append(f"PNG file '{PNG_FILE_PATH}'")
    if not os.path.exists(JSON_FILE_PATH):
        missing_files.append(f"JSON file '{JSON_FILE_PATH}'")
    
    if missing_files:
        print(f"Error: {' and '.join(missing_files)} not found!")
        sys.exit(1)
    
    asyncio.run(main())