# Generated by Django 5.2.2 on 2025-06-07 18:49

import hack4impact.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('dirname', models.CharField(default='general', max_length=255)),
                ('file', models.FileField(upload_to=hack4impact.api.models.set_document_upload_to)),
            ],
        ),
    ]
